---
config:
   flowchart:
    nodeSpacing: 100
    rankSpacing: 120
---
flowchart TD

n1["`**1**
**mod 6**: 1`"]
n3["`**3**
**mod 6**: 3`"]-->n10
n10["`**10**
**mod 6**: 4`"]-->n5
n5["`**5**
**mod 6**: 5`"]-->n16
n16["`**16**
**mod 6**: 4`"]-->n8
n8["`**8**
**mod 6**: 2`"]-->n4
n4["`**4**
**mod 6**: 4`"]-->n2
n2["`**2**
**mod 6**: 2`"]-->n1
n6["`**6**
**mod 6**: 0`"]-->n3
n7["`**7**
**mod 6**: 1`"]-->n22
n22["`**22**
**mod 6**: 4`"]-->n11
n11["`**11**
**mod 6**: 5`"]-->n34
n34["`**34**
**mod 6**: 4`"]-->n17
n17["`**17**
**mod 6**: 5`"]-->n52
n52["`**52**
**mod 6**: 4`"]-->n26
n26["`**26**
**mod 6**: 2`"]-->n13
n13["`**13**
**mod 6**: 1`"]-->n40
n40["`**40**
**mod 6**: 4`"]-->n20
n20["`**20**
**mod 6**: 2`"]-->n10
n9["`**9**
**mod 6**: 3`"]-->n28
n28["`**28**
**mod 6**: 4`"]-->n14
n14["`**14**
**mod 6**: 2`"]-->n7
n12["`**12**
**mod 6**: 0`"]-->n6
n15["`**15**
**mod 6**: 3`"]-->n46
n46["`**46**
**mod 6**: 4`"]-->n23
n23["`**23**
**mod 6**: 5`"]-->n70
n70["`**70**
**mod 6**: 4`"]-->n35
n35["`**35**
**mod 6**: 5`"]-->n106
n106["`**106**
**mod 6**: 4`"]-->n53
n53["`**53**
**mod 6**: 5`"]-->n160
n160["`**160**
**mod 6**: 4`"]-->n80
n80["`**80**
**mod 6**: 2`"]-->n40
n18["`**18**
**mod 6**: 0`"]-->n9
n19["`**19**
**mod 6**: 1`"]-->n58
n58["`**58**
**mod 6**: 4`"]-->n29
n29["`**29**
**mod 6**: 5`"]-->n88
n88["`**88**
**mod 6**: 4`"]-->n44
n44["`**44**
**mod 6**: 2`"]-->n22
n21["`**21**
**mod 6**: 3`"]-->n64
n64["`**64**
**mod 6**: 4`"]-->n32
n32["`**32**
**mod 6**: 2`"]-->n16
n24["`**24**
**mod 6**: 0`"]-->n12
n25["`**25**
**mod 6**: 1`"]-->n76
n76["`**76**
**mod 6**: 4`"]-->n38
n38["`**38**
**mod 6**: 2`"]-->n19