---
config:
   flowchart:
    nodeSpacing: 100
    rankSpacing: 120
---
flowchart TD
classDef red stroke:red,stroke-width: 3px;
classDef green stroke:green,stroke-width: 3px;
classDef blue stroke:blue,stroke-width: 3px;

n1["`**1**
**mod 6**: 1`"]:::green
n11["`**11**
**mod 6**: 5`"]:::green-->n34
n34["`**34**
**mod 6**: 4`"]-->n17
n17["`**17**
**mod 6**: 5`"]:::green-->n52
n52["`**52**
**mod 6**: 4`"]-->n26
n26["`**26**
**mod 6**: 2`"]-->n13
n13["`**13**
**mod 6**: 1`"]:::green-->n40
n40["`**40**
**mod 6**: 4`"]-->n20
n20["`**20**
**mod 6**: 2`"]-->n10
n10["`**10**
**mod 6**: 4`"]-->n5
n5["`**5**
**mod 6**: 5`"]:::green-->n16
n16["`**16**
**mod 6**: 4`"]-->n8
n8["`**8**
**mod 6**: 2`"]-->n4
n4["`**4**
**mod 6**: 4`"]-->n2
n2["`**2**
**mod 6**: 2`"]-->n1