---
config:
   flowchart:
    nodeSpacing: 100
    rankSpacing: 120
---
flowchart TD
classDef red stroke:red,stroke-width: 3px;
classDef green stroke:green,stroke-width: 3px;
classDef blue stroke:blue,stroke-width: 3px;

n1["`**1**
**MapToOne**: [0]

**Mod6**: 1`"]:::green
n2["`**2**
**MapToOne**: [1]

**Mod6**: 2`"]-->n1
n4["`**4**
**MapToOne**: [2]

**Mod6**: 4`"]-->n2
n8["`**8**
**MapToOne**: [3]

**Mod6**: 2`"]-->n4
n16["`**16**
**MapToOne**: [4]

**Mod6**: 4`"]-->n8
n5["`**5**
**MapToOne**: [4, 0]

**Mod6**: 5`"]:::green-->n16
n10["`**10**
**MapToOne**: [4, 1]

**Mod6**: 4`"]-->n5
n3["`**3**
**MapToOne**: [4, 1, 0]

**Mod6**: 3`"]:::green-->n10
n6["`**6**
**MapToOne**: [4, 1, 1]

**Mod6**: 0`"]-->n3
n20["`**20**
**MapToOne**: [4, 2]

**Mod6**: 2`"]-->n10
n40["`**40**
**MapToOne**: [4, 3]

**Mod6**: 4`"]-->n20
n13["`**13**
**MapToOne**: [4, 3, 0]

**Mod6**: 1`"]:::green-->n40
n26["`**26**
**MapToOne**: [4, 3, 1]

**Mod6**: 2`"]-->n13
n52["`**52**
**MapToOne**: [4, 3, 2]

**Mod6**: 4`"]-->n26
n17["`**17**
**MapToOne**: [4, 3, 2, 0]

**Mod6**: 5`"]:::green-->n52
n34["`**34**
**MapToOne**: [4, 3, 2, 1]

**Mod6**: 4`"]-->n17
n11["`**11**
**MapToOne**: [4, 3, 2, 1, 0]

**Mod6**: 5`"]:::green-->n34
n22["`**22**
**MapToOne**: [4, 3, 2, 1, 1]

**Mod6**: 4`"]-->n11
n7["`**7**
**MapToOne**: [4, 3, 2, 1, 1, 0]

**Mod6**: 1`"]:::green-->n22
n14["`**14**
**MapToOne**: [4, 3, 2, 1, 1, 1]

**Mod6**: 2`"]-->n7
n28["`**28**
**MapToOne**: [4, 3, 2, 1, 1, 2]

**Mod6**: 4`"]-->n14
n9["`**9**
**MapToOne**: [4, 3, 2, 1, 1, 2, 0]

**Mod6**: 3`"]:::green-->n28
n12["`**12**
**MapToOne**: [4, 1, 2]

**Mod6**: 0`"]-->n6
n80["`**80**
**MapToOne**: [4, 4]

**Mod6**: 2`"]-->n40
n160["`**160**
**MapToOne**: [4, 5]

**Mod6**: 4`"]-->n80
n53["`**53**
**MapToOne**: [4, 5, 0]

**Mod6**: 5`"]:::green-->n160
n106["`**106**
**MapToOne**: [4, 5, 1]

**Mod6**: 4`"]-->n53
n35["`**35**
**MapToOne**: [4, 5, 1, 0]

**Mod6**: 5`"]:::green-->n106
n70["`**70**
**MapToOne**: [4, 5, 1, 1]

**Mod6**: 4`"]-->n35
n23["`**23**
**MapToOne**: [4, 5, 1, 1, 0]

**Mod6**: 5`"]:::green-->n70
n46["`**46**
**MapToOne**: [4, 5, 1, 1, 1]

**Mod6**: 4`"]-->n23
n15["`**15**
**MapToOne**: [4, 5, 1, 1, 1, 0]

**Mod6**: 3`"]:::green-->n46
n18["`**18**
**MapToOne**: [4, 3, 2, 1, 1, 2, 1]

**Mod6**: 0`"]-->n9
n44["`**44**
**MapToOne**: [4, 3, 2, 1, 2]

**Mod6**: 2`"]-->n22
n88["`**88**
**MapToOne**: [4, 3, 2, 1, 3]

**Mod6**: 4`"]-->n44
n29["`**29**
**MapToOne**: [4, 3, 2, 1, 3, 0]

**Mod6**: 5`"]:::green-->n88
n58["`**58**
**MapToOne**: [4, 3, 2, 1, 3, 1]

**Mod6**: 4`"]-->n29
n19["`**19**
**MapToOne**: [4, 3, 2, 1, 3, 1, 0]

**Mod6**: 1`"]:::green-->n58
n32["`**32**
**MapToOne**: [5]

**Mod6**: 2`"]-->n16
n64["`**64**
**MapToOne**: [6]

**Mod6**: 4`"]-->n32
n21["`**21**
**MapToOne**: [6, 0]

**Mod6**: 3`"]:::green-->n64
n24["`**24**
**MapToOne**: [4, 1, 3]

**Mod6**: 0`"]-->n12
n38["`**38**
**MapToOne**: [4, 3, 2, 1, 3, 1, 1]

**Mod6**: 2`"]-->n19
n76["`**76**
**MapToOne**: [4, 3, 2, 1, 3, 1, 2]

**Mod6**: 4`"]-->n38
n25["`**25**
**MapToOne**: [4, 3, 2, 1, 3, 1, 2, 0]

**Mod6**: 1`"]:::green-->n76